services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=medicareuser
      - POSTGRES_PASSWORD=medicarepass
      - POSTGRES_DB=medicaredb
    ports:
      - '5400:5432'
    volumes:
      - postgres_data_new4:/var/lib/postgresql/data

volumes:
      postgres_data_new4: