version: '3.8'

services:
  db:
    image: python:3.11-slim
    working_dir: /app
    environment:
      - OLLAMA_HOST=http://ollama:11434
      
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "pip install uvicorn httpx &&
      uvicorn main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - ollama
    networks:
      - backend
    ollama:
      image: ollama/ollama
      ports:
        - "11434:11434"
      volumes:
        - ollama_models:/root/.ollama
      networks:
        - backend
      privileged: true

volumes:
  ollama_models:

networks:
  backend:
    driver: bridge
